// Generated by gencpp from file node_client/client.msg
// DO NOT EDIT!


#ifndef NODE_CLIENT_MESSAGE_CLIENT_H
#define NODE_CLIENT_MESSAGE_CLIENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_client
{
template <class ContainerAllocator>
struct client_
{
  typedef client_<ContainerAllocator> Type;

  client_()
    : type(0)
    , data()  {
    }
  client_(const ContainerAllocator& _alloc)
    : type(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::node_client::client_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_client::client_<ContainerAllocator> const> ConstPtr;

}; // struct client_

typedef ::node_client::client_<std::allocator<void> > client;

typedef boost::shared_ptr< ::node_client::client > clientPtr;
typedef boost::shared_ptr< ::node_client::client const> clientConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_client::client_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_client::client_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_client

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'node_client': ['/home/pi/Car/src/node_client/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_client::client_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_client::client_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_client::client_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_client::client_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_client::client_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_client::client_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_client::client_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a37de7fa0c884435aa5ee4c76f9a1011";
  }

  static const char* value(const ::node_client::client_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa37de7fa0c884435ULL;
  static const uint64_t static_value2 = 0xaa5ee4c76f9a1011ULL;
};

template<class ContainerAllocator>
struct DataType< ::node_client::client_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_client/client";
  }

  static const char* value(const ::node_client::client_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_client::client_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 type\n\
string data\n\
";
  }

  static const char* value(const ::node_client::client_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_client::client_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct client_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_client::client_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_client::client_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.type);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_CLIENT_MESSAGE_CLIENT_H
