// Generated by gencpp from file node_ultrasonic/ultr.msg
// DO NOT EDIT!


#ifndef NODE_ULTRASONIC_MESSAGE_ULTR_H
#define NODE_ULTRASONIC_MESSAGE_ULTR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_ultrasonic
{
template <class ContainerAllocator>
struct ultr_
{
  typedef ultr_<ContainerAllocator> Type;

  ultr_()
    : distance(0.0)  {
    }
  ultr_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::node_ultrasonic::ultr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_ultrasonic::ultr_<ContainerAllocator> const> ConstPtr;

}; // struct ultr_

typedef ::node_ultrasonic::ultr_<std::allocator<void> > ultr;

typedef boost::shared_ptr< ::node_ultrasonic::ultr > ultrPtr;
typedef boost::shared_ptr< ::node_ultrasonic::ultr const> ultrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_ultrasonic::ultr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_ultrasonic::ultr_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_ultrasonic

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'node_ultrasonic': ['/home/pi/Car/src/node_ultrasonic/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_ultrasonic::ultr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_ultrasonic::ultr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_ultrasonic::ultr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_ultrasonic::ultr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_ultrasonic::ultr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_ultrasonic::ultr_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_ultrasonic::ultr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::node_ultrasonic::ultr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::node_ultrasonic::ultr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_ultrasonic/ultr";
  }

  static const char* value(const ::node_ultrasonic::ultr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_ultrasonic::ultr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n\
";
  }

  static const char* value(const ::node_ultrasonic::ultr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_ultrasonic::ultr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_ultrasonic::ultr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_ultrasonic::ultr_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_ULTRASONIC_MESSAGE_ULTR_H
