# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from node_motion/motion.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motion(genpy.Message):
  _md5sum = "30faa4135c68a2443be6182d9fd899f7"
  _type = "node_motion/motion"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 lf_forward
int32 ri_forward
int32 lf_back
int32 ri_back
"""
  __slots__ = ['lf_forward','ri_forward','lf_back','ri_back']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       lf_forward,ri_forward,lf_back,ri_back

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motion, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.lf_forward is None:
        self.lf_forward = 0
      if self.ri_forward is None:
        self.ri_forward = 0
      if self.lf_back is None:
        self.lf_back = 0
      if self.ri_back is None:
        self.ri_back = 0
    else:
      self.lf_forward = 0
      self.ri_forward = 0
      self.lf_back = 0
      self.ri_back = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.lf_forward, _x.ri_forward, _x.lf_back, _x.ri_back))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.lf_forward, _x.ri_forward, _x.lf_back, _x.ri_back,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.lf_forward, _x.ri_forward, _x.lf_back, _x.ri_back))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.lf_forward, _x.ri_forward, _x.lf_back, _x.ri_back,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4i = struct.Struct("<4i")
