// Generated by gencpp from file node_infrared/infr.msg
// DO NOT EDIT!


#ifndef NODE_INFRARED_MESSAGE_INFR_H
#define NODE_INFRARED_MESSAGE_INFR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_infrared
{
template <class ContainerAllocator>
struct infr_
{
  typedef infr_<ContainerAllocator> Type;

  infr_()
    : left(0)
    , right(0)  {
    }
  infr_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef int8_t _left_type;
  _left_type left;

   typedef int8_t _right_type;
  _right_type right;




  typedef boost::shared_ptr< ::node_infrared::infr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_infrared::infr_<ContainerAllocator> const> ConstPtr;

}; // struct infr_

typedef ::node_infrared::infr_<std::allocator<void> > infr;

typedef boost::shared_ptr< ::node_infrared::infr > infrPtr;
typedef boost::shared_ptr< ::node_infrared::infr const> infrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_infrared::infr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_infrared::infr_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_infrared

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'node_infrared': ['/home/pi/Car/src/node_infrared/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_infrared::infr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_infrared::infr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_infrared::infr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_infrared::infr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_infrared::infr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_infrared::infr_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_infrared::infr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24825b8956c21f4c3dd28a5a4d09322c";
  }

  static const char* value(const ::node_infrared::infr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24825b8956c21f4cULL;
  static const uint64_t static_value2 = 0x3dd28a5a4d09322cULL;
};

template<class ContainerAllocator>
struct DataType< ::node_infrared::infr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_infrared/infr";
  }

  static const char* value(const ::node_infrared::infr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_infrared::infr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 left\n\
int8 right\n\
";
  }

  static const char* value(const ::node_infrared::infr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_infrared::infr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct infr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_infrared::infr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_infrared::infr_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int8_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int8_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_INFRARED_MESSAGE_INFR_H
